hyperskill_project:
  id: 180
  ide_files: https://stepik.org/media/attachments/lesson/529086/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 917
  step: 13088
  is_completed: false
- id: 918
  step: 13089
  is_completed: false
- id: 919
  step: 13090
  is_completed: false
- id: 920
  step: 13091
  is_completed: false
- id: 921
  step: 13092
  is_completed: false
